'use client'

import { FormEvent, useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

const empty = { title: '', slug: '', excerpt: '', body: '', category: 'Reminder', status: 'published' }
export default function AdminPage() {
  const [loggedIn, setLoggedIn] = useState(false); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [form, setForm] = useState(empty); const [message, setMessage] = useState(''); const [count, setCount] = useState(0)
  useEffect(() => { setLoggedIn(sessionStorage.getItem('sukoon-admin') === '1') }, [])
  async function save(event: FormEvent) { event.preventDefault(); const { error } = await createClient().from('site_content').upsert({ ...form, is_featured: false }, { onConflict: 'slug' }); setMessage(error ? 'Could not save. Check your Supabase table policies.' : 'Published to the site.'); if (!error) setForm(empty) }
  async function loadCount() { const { count } = await createClient().from('subscribers').select('id', { count: 'exact', head: true }); setCount(count ?? 0) }
  if (!loggedIn) return <main className="min-h-screen bg-paper px-6 py-10"><div className="mx-auto max-w-md"><a href="/" className="font-serif text-2xl">sukoon<span className="text-terracotta">.</span></a><div className="mt-20 rounded-[2rem] border border-border bg-card p-8"><p className="eyebrow">Private studio</p><h1 className="mt-3 font-serif text-4xl">Admin sign in.</h1><form className="mt-8 flex flex-col gap-4" onSubmit={event => { event.preventDefault(); if (username === 'admin' && password === 'admin') { sessionStorage.setItem('sukoon-admin', '1'); setLoggedIn(true) } else setMessage('Use the provided admin credentials.') }}><input aria-label="Username" placeholder="Username" value={username} onChange={e => setUsername(e.target.value)} className="rounded-xl border border-border bg-paper px-4 py-3" /><input aria-label="Password" type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} className="rounded-xl border border-border bg-paper px-4 py-3" />{message && <p className="text-sm text-terracotta">{message}</p>}<button className="rounded-full bg-ink px-5 py-3 text-sm text-white">Enter studio</button></form></div></div></main>
  return <main className="min-h-screen bg-paper px-6 py-10"><div className="mx-auto max-w-4xl"><div className="flex items-center justify-between"><a href="/" className="font-serif text-2xl">sukoon<span className="text-terracotta">.</span></a><button className="text-sm underline" onClick={() => { sessionStorage.removeItem('sukoon-admin'); setLoggedIn(false) }}>Sign out</button></div><div className="mt-16"><p className="eyebrow">Content studio</p><h1 className="mt-3 font-serif text-5xl">Write something worth returning to.</h1><p className="mt-4 max-w-xl text-muted-foreground">Publish a reminder, letter, course note, or journal entry directly into Supabase.</p><div className="mt-10 rounded-[2rem] border border-border bg-card p-8"><form onSubmit={save} className="flex flex-col gap-4"><input required placeholder="Title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value, slug: form.slug || e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') })} className="rounded-xl border border-border bg-paper px-4 py-3" /><input required placeholder="Slug" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} className="rounded-xl border border-border bg-paper px-4 py-3" /><input placeholder="Category" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="rounded-xl border border-border bg-paper px-4 py-3" /><input required placeholder="Short excerpt" value={form.excerpt} onChange={e => setForm({ ...form, excerpt: e.target.value })} className="rounded-xl border border-border bg-paper px-4 py-3" /><textarea required placeholder="Body" rows={9} value={form.body} onChange={e => setForm({ ...form, body: e.target.value })} className="rounded-xl border border-border bg-paper px-4 py-3" /><button className="rounded-full bg-ink px-5 py-3 text-sm text-white">Publish content</button></form>{message && <p className="mt-4 text-sm text-olive">{message}</p>}</div><div className="mt-6 flex items-center justify-between rounded-2xl bg-sand p-6"><div><p className="eyebrow">Subscribers</p><p className="mt-2 font-serif text-3xl">{count} saved emails</p></div><button onClick={loadCount} className="rounded-full border border-ink/20 px-4 py-2 text-sm">Refresh count</button></div></div></div></main>
}
